"""business schema

Revision ID: d2d2999eca0e
Revises:
Create Date: 2026-09-27 19:41:20.240759

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_business"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS business")
    op.execute("CREATE SEQUENCE business.order_number_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="business",
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "sequence_no",
            sa.BigInteger(),
            server_default=sa.text("nextval('business.order_number_seq')"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("customer_name", sa.String(), nullable=False),
        sa.Column("delivery_address", sa.String(), nullable=False),
        sa.Column("total_cents", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("total_cents >= 0"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sequence_no"),
        schema="business",
    )
    op.create_index(
        op.f("ix_business_orders_created_by"),
        "orders",
        ["created_by"],
        unique=False,
        schema="business",
    )
    op.create_table(
        "products",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price_cents", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.CheckConstraint("price_cents >= 0"),
        sa.PrimaryKeyConstraint("id"),
        schema="business",
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.String(), nullable=False),
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_cents", sa.BigInteger(), nullable=False),
        sa.Column("line_total_cents", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("line_total_cents >= 0"),
        sa.CheckConstraint("quantity > 0"),
        sa.CheckConstraint("unit_price_cents >= 0"),
        sa.ForeignKeyConstraint(["order_id"], ["business.orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["business.products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="business",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_items", schema="business")
    op.drop_table("products", schema="business")
    op.drop_index(op.f("ix_business_orders_created_by"), table_name="orders", schema="business")
    op.drop_table("orders", schema="business")
    op.drop_table("customers", schema="business")
    op.execute("DROP SEQUENCE business.order_number_seq")
    op.execute("DROP SCHEMA business")
    # ### end Alembic commands ###
